@startuml
left to right direction
skinparam packageStyle rectangle

actor "Content Creator" as creator

package "Phân hệ Media Library" {
  usecase "Tải lên Media (Local/Drive)" as UC06a
  usecase "Quản lý Thư mục (Media Folders)" as UC06b
}

creator --> UC06a
creator --> UC06b

@enduml
